apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-failover-nginx
  namespace: demo-failover
  labels:
    app: demo-failover-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-failover-nginx
  template:
    metadata:
      labels:
        app: demo-failover-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
