apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: demo-twinx-namespace-policy
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: demo-twinx
  placement:
    clusterAffinity:
      labelSelector:
        matchLabels:
          scalex.io/role: gpu-render
