apiVersion: v1
kind: Service
metadata:
  name: demo-twinx-nginx
  namespace: demo-twinx
  labels:
    app: demo-twinx-nginx
    scalex.io/target: twinx
spec:
  type: ClusterIP
  selector:
    app: demo-twinx-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
