apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-appset-data-nginx
  namespace: demo-appset-data
  labels:
    app: demo-appset-data-nginx
    scalex.io/demo: appset-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-appset-data-nginx
  template:
    metadata:
      labels:
        app: demo-appset-data-nginx
        scalex.io/demo: appset-data
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
