apiVersion: v1
kind: Service
metadata:
  name: demo-multi-data-nginx
  namespace: demo-multi-rebalance
spec:
  selector:
    app: demo-multi-data-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
