apiVersion: apps.karmada.io/v1alpha1
kind: WorkloadRebalancer
metadata:
  name: demo-noexecute-eviction-rebalance
spec:
  workloads:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: demo-noexecute-eviction
      name: demo-noexecute-eviction-nginx
