---
apiVersion: v1
kind: Service
metadata:
  name: omniverse-nucleus-headless
  namespace: omniverse
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: omniverse-nucleus
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: omniverse-nucleus
  ports:
    - name: web
      port: 8080
      targetPort: web
