apiVersion: v1
kind: Service
metadata:
  name: demo-estimator-aggregated-nginx
  namespace: demo-scheduler-estimator
spec:
  selector:
    app: demo-estimator-aggregated-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
