apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-scalex-data-nginx
  namespace: demo-scalex-role
  labels:
    app: demo-scalex-data-nginx
    scalex.io/workload: data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-scalex-data-nginx
  template:
    metadata:
      labels:
        app: demo-scalex-data-nginx
        scalex.io/workload: data
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
