apiVersion: v1
kind: Service
metadata:
  name: demo-noexecute-eviction-nginx
  namespace: demo-noexecute-eviction
spec:
  selector:
    app: demo-noexecute-eviction-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
