apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-twinx-auto-nginx-policy
  namespace: demo-twinx-auto
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: demo-twinx-auto-nginx
    - apiVersion: v1
      kind: Service
      name: demo-twinx-auto-nginx
  placement:
    clusterAffinity:
      labelSelector:
        matchLabels:
          scalex.io/role: gpu-render
