apiVersion: apps.karmada.io/v1alpha1
kind: WorkloadRebalancer
metadata:
  name: demo-pull-edge-rebalance-run
spec:
  workloads:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: demo-scalex-role
      name: demo-scalex-edge-nginx
