apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-override-platform-data
  namespace: demo-override-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 64Mi
