apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-weighted-nginx-policy
  namespace: demo-weighted
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: demo-weighted-nginx
    - apiVersion: v1
      kind: Service
      name: demo-weighted-nginx
  placement:
    clusterAffinity:
      clusterNames:
        - twinx
        - edgex
        - datax
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - twinx
            weight: 4
          - targetCluster:
              clusterNames:
                - edgex
            weight: 1
          - targetCluster:
              clusterNames:
                - datax
            weight: 1
