apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: demo-namespace-policy
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: demo
  placement:
    clusterAffinity:
      clusterNames:
        - twinx
        - edgex
        - datax
