apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-multi-render-nginx
  namespace: demo-multi-rebalance
  labels:
    app: demo-multi-render-nginx
    scalex.io/workload: render
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-multi-render-nginx
  template:
    metadata:
      labels:
        app: demo-multi-render-nginx
        scalex.io/workload: render
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
